// ─── CJS-compatible blog seed data ───────────────────────────────────────────
// Mirrors src/data/blogPosts.js but in CommonJS so server migrations can use it.
// When you add posts to blogPosts.js, add them here too (or manage via the admin).

const SEED_POSTS = [
  {
    slug: 'how-certo-orders-apple-from-us',
    title: 'How Certo Orders Apple Products Directly from the US',
    excerpt: "Every device we sell starts as a real order placed on apple.com — no middlemen, no grey market. Here's exactly how it works.",
    category: 'How Certo Works',
    readTime: '5 min read',
    date: 'May 2025',
    featured: true,
    tags: ['Certo', 'Apple US', 'How It Works', 'Sourcing'],
    relatedCategories: ['iPhone', 'Mac', 'iPad', 'Apple Watch', 'AirPods'],
    emoji: '🛒',
    sections: [
      { heading: 'It Starts on Apple.com', body: "When you place an order with Certo, we go directly to apple.com — the same website any customer in the United States would use. We place the order under a verified US address, pay with a US-registered payment method, and the device ships from Apple's own warehouse. This is not a grey market operation. The device goes from Apple's shelf to our shipping handler — no detours." },
      { heading: 'Air Freight to Lagos', body: ['Once the device arrives at our US logistics partner, we consolidate shipments and send them via air freight directly to Murtala Muhammed Airport in Lagos. Every shipment is declared accurately at customs — duties are paid in full.', 'The entire journey from Apple US to your door in Lagos typically takes 10–18 business days.'] },
      { heading: 'Serial Verification Before Delivery', body: "Before any device leaves our hands, we verify the serial number on Apple's coverage checker at checkcoverage.apple.com. We confirm it is genuine, the warranty start date matches the purchase date, and it has never been previously activated." },
      { heading: 'The Certo Certificate', body: 'Every order comes with a Certo Certificate of Purchase — a publicly verifiable record showing the serial number, chain of custody, and the exact route the device took from Apple to you.' },
    ],
  },
  {
    slug: 'why-buy-apple-from-us-not-local-vendors',
    title: 'Why Apple from the US Beats Local Nigerian Vendors',
    excerpt: 'The iPhone at your local phone market might look identical to one ordered from Apple US. Here is why it almost certainly is not — and why it matters.',
    category: 'Authenticity',
    readTime: '6 min read',
    date: 'May 2025',
    featured: true,
    tags: ['Authenticity', 'Fake iPhone', 'Nigeria Market', 'Apple US'],
    relatedCategories: ['iPhone', 'Mac', 'iPad'],
    emoji: '🔍',
    sections: [
      { heading: 'The Problem with the Local Market', body: 'Computer Village in Ikeja and similar markets in Lagos, Abuja, and Port Harcourt are full of iPhones. Most sellers claim their devices are "brand new, original." Some of them are telling the truth. Most are not. The grey market for iPhones in Nigeria operates at scale — devices are sourced from Hong Kong, Dubai, China, and occasionally the US, at various points in the supply chain, with varying levels of authenticity.' },
      { heading: 'What "UK Used" and "US Used" Actually Means', body: ['These terms are used loosely. A "US Used" iPhone might genuinely be a device purchased and used in the US — or it might be a refurbished device with a replaced battery and screen that was never near the United States.', 'There is no industry standard or verification process at the local market level. The seller tells you what they think will close the sale.'] },
      { heading: 'How to Actually Verify an iPhone', body: ['Go to checkcoverage.apple.com and enter the serial number. A legitimate iPhone will show purchase date, warranty status, and coverage details.', 'Also check: Settings → General → About. If the model number starts with M, it was sold new. If it starts with F, it was factory refurbished. If it starts with N, it was a replacement device. If the serial shows up as invalid on Apple\'s site, the phone is either counterfeit or its serial has been manipulated.'] },
    ],
  },
  {
    slug: 'best-macbook-for-you-nigeria',
    title: 'Best MacBook for You in Nigeria — 2025 Buyer\'s Guide',
    excerpt: 'MacBook Air or MacBook Pro? M2 or M3? 13-inch or 15-inch? This guide cuts through the specs and tells you exactly which MacBook fits your life.',
    category: 'Buying Guide',
    readTime: '7 min read',
    date: 'May 2025',
    featured: false,
    tags: ['MacBook', 'Mac', 'Buying Guide', 'Nigeria', '2025'],
    relatedCategories: ['Mac'],
    emoji: '💻',
    sections: [
      { heading: 'MacBook Air M2 — Best Value', body: "The MacBook Air M2 (₦900,000–₦1,100,000) is the best laptop for most people. It handles everything short of video editing and 3D rendering without breaking a sweat, the battery lasts 15–18 hours, and the fanless design means it is completely silent. If you are a student, writer, marketer, or business professional who does not edit video, this is your laptop." },
      { heading: 'MacBook Air M3 — Upgrade Worth Having', body: 'The M3 chip improves single-core performance by 20% over M2, adds hardware ray tracing for gaming, and supports two external displays (M2 Air only supports one). At ₦1,200,000–₦1,500,000, the M3 Air is worth it if you plan to keep the laptop for 5+ years or need the dual display support.' },
      { heading: 'MacBook Pro — When You Actually Need It', body: ['The MacBook Pro (M3 Pro or M3 Max) is for sustained professional workloads — video editing in 4K/8K, music production with hundreds of tracks, 3D modeling, or software compilation. The fan allows the chip to run at full speed continuously without throttling.', 'If your heaviest task is running Figma or editing photos in Lightroom, you do not need a MacBook Pro. Get the Air and invest the difference in more RAM or storage.'] },
    ],
  },
  {
    slug: 'iphone-screen-prices-nigeria-2025',
    title: 'iPhone Screen Replacement Prices in Nigeria (2025)',
    excerpt: 'A cracked iPhone screen in Nigeria can cost anywhere from ₦30,000 to ₦200,000 to fix. This guide explains why — and how to avoid getting overcharged.',
    category: 'Repairs & Costs',
    readTime: '5 min read',
    date: 'May 2025',
    featured: false,
    tags: ['iPhone', 'Screen Repair', 'Nigeria', 'Prices', 'Repairs'],
    relatedCategories: ['iPhone'],
    emoji: '📱',
    sections: [
      { heading: 'Why iPhone Screen Repairs Are Expensive', body: 'iPhone screens are not just glass — they are tightly integrated OLED assemblies that include the display, touch digitizer, True Tone calibration data, and Face ID sensors. Replacing a screen without Apple\'s proprietary tools can break Face ID and True Tone permanently. This is why genuine iPhone repairs are expensive and why "cheap" repairs at local shops usually involve third-party displays.' },
      { heading: 'Price Ranges by Model (Lagos Market 2025)', body: ['iPhone X / XS / XS Max: ₦25,000–₦45,000 (third-party) / ₦60,000–₦85,000 (OEM quality)', 'iPhone 11 / 11 Pro / 11 Pro Max: ₦30,000–₦55,000 / ₦70,000–₦100,000', 'iPhone 12 / 12 Pro: ₦40,000–₦65,000 / ₦90,000–₦120,000', 'iPhone 13 / 13 Pro: ₦50,000–₦80,000 / ₦110,000–₦150,000', 'iPhone 14 / 14 Pro: ₦65,000–₦95,000 / ₦130,000–₦180,000', 'iPhone 15 / 15 Pro: ₦80,000–₦120,000 / ₦160,000–₦220,000'] },
      { heading: 'Third-Party vs OEM vs Apple', body: 'Third-party screens use non-Apple displays — colors look washed out, True Tone stops working, and touch sensitivity is reduced. OEM-quality screens use displays pulled from original iPhones — they look identical to the original. Apple authorized repair uses genuine parts and preserves all functionality including Face ID. Always ask specifically which type of screen the repair shop is using before you agree to a price.' },
    ],
  },
  {
    slug: 'iphone-battery-prices-nigeria-2025',
    title: 'iPhone Battery Replacement Prices in Nigeria (2025)',
    excerpt: 'Battery health dropping below 80%? Here is what a battery replacement costs across Nigeria, which shops are trustworthy, and when to replace vs buy new.',
    category: 'Repairs & Costs',
    readTime: '4 min read',
    date: 'May 2025',
    featured: false,
    tags: ['iPhone', 'Battery', 'Nigeria', 'Repairs', 'Prices'],
    relatedCategories: ['iPhone'],
    emoji: '🔋',
    sections: [
      { heading: 'When Should You Replace the Battery?', body: "Go to Settings → Battery → Battery Health & Charging. Apple recommends replacement when health drops below 80%. At this point, your iPhone throttles performance to prevent unexpected shutdowns. Below 70%, the phone becomes unreliable for daily use." },
      { heading: 'Battery Replacement Prices in Nigeria (2025)', body: ['iPhone 8 / X: ₦12,000–₦20,000', 'iPhone 11 series: ₦15,000–₦25,000', 'iPhone 12 series: ₦18,000–₦28,000', 'iPhone 13 series: ₦20,000–₦32,000', 'iPhone 14 series: ₦25,000–₦40,000', 'iPhone 15 series: ₦30,000–₦50,000', 'Note: Apple charges $99 for out-of-warranty battery replacement. AppleCare+ covers battery replacement for free if health drops below 80%.'] },
      { heading: 'DIY Battery Replacement — Is It Worth It?', body: 'iFixit sells iPhone battery kits for $30–$50 that include all the tools. The procedure is well-documented and manageable for the technically inclined. However, replacing an iPhone battery without Apple\'s proprietary software means the battery health display in Settings will show "Service Recommended" — the phone functions normally but the accurate health percentage is lost. For most people, professional replacement is better.' },
    ],
  },
  {
    slug: 'how-to-spot-fake-tampered-iphone',
    title: 'How to Know If Your iPhone Is Fake or Has Been Tampered With',
    excerpt: 'Counterfeit iPhones, replaced screens, swapped batteries, and cloned serials are common in Nigeria. This is how to check yours in under five minutes.',
    category: 'Authenticity',
    readTime: '6 min read',
    date: 'May 2025',
    featured: true,
    tags: ['Fake iPhone', 'Authenticity', 'Verification', 'Nigeria'],
    relatedCategories: ['iPhone'],
    emoji: '🕵️',
    sections: [
      { heading: 'Step 1 — Check the Serial on Apple\'s Website', body: "Go to checkcoverage.apple.com and enter the serial number (found in Settings → General → About). A real iPhone will show the model, purchase date, and warranty status. If the site says the serial is invalid or shows a different model than what you're holding, the device has been tampered with or is counterfeit." },
      { heading: 'Step 2 — Check the IMEI', body: "Dial *#06# to display the IMEI. Cross-reference this IMEI with the one printed on the SIM tray (iPhone 14 and below). On iPhone 15+, the IMEI is in Settings → General → About. If the numbers do not match, the SIM tray has been replaced — a common practice with stolen or refurbished phones that hides the device's true history." },
      { heading: 'Step 3 — Look for Signs of Repair', body: ['Open Settings → Privacy & Security → Analytics & Improvements → Analytics Data and look for files containing "panic" — these suggest hardware issues.', 'Check if Face ID works correctly. A replaced screen that was not properly calibrated using Apple\'s proprietary tools will cause Face ID errors.', 'Look at the screws on the bottom of the iPhone (near the Lightning/USB-C port) under a torch. Original screws are perfectly aligned pentalobe screws. Replaced screws often show stripped heads or mismatched metal finish.'] },
      { heading: 'Step 4 — Battery and Screen Health', body: "Go to Settings → Battery → Battery Health. If it shows 'Service Recommended' or 'Unknown Part,' the battery has been replaced with a non-Apple battery. Go to Settings → General → About and scroll to 'Display.' If it says 'Unknown Part,' the screen has been replaced with a third-party display." },
    ],
  },
  {
    slug: 'iphone-vs-android-nigeria-2025',
    title: 'iPhone vs Android in Nigeria — Which Should You Buy?',
    excerpt: 'The honest answer depends on how you use your phone. This guide breaks down every factor that matters for Nigerian users in 2025.',
    category: 'Buying Guide',
    readTime: '8 min read',
    date: 'May 2025',
    featured: false,
    tags: ['iPhone', 'Android', 'Nigeria', 'Comparison', '2025'],
    relatedCategories: ['iPhone'],
    emoji: '⚖️',
    sections: [
      { heading: 'Software Updates', body: 'Apple supports iPhones for 6–7 years of major iOS updates. The iPhone 12 (released 2020) runs iOS 18 in 2025. Most Android flagships receive 3–4 years of major updates, with Google Pixel and Samsung being the exceptions at 7 years. For long-term value in Nigeria where device replacement cycles are longer, iOS support is a meaningful advantage.' },
      { heading: 'The Repair Ecosystem', body: "This is Android's biggest advantage in Nigeria. Samsung, Tecno, and Infinix parts are widely available and cheap. iPhone parts are harder to source, require specialist tools, and are significantly more expensive. If you cannot afford AppleCare+ and have a history of breaking phones, an Android flagship may be more practical." },
      { heading: 'Resale Value', body: 'iPhones hold their resale value far better than Android phones in Nigeria. An iPhone 13 bought in 2021 for ₦600,000 resells for ₦350,000–₦400,000 in 2025. A Samsung Galaxy S22 bought for the same price resells for ₦150,000–₦200,000. If you plan to trade up every few years, iPhones preserve your capital better.' },
    ],
  },
  {
    slug: 'best-iphone-for-your-budget-nigeria-2025',
    title: 'Best iPhone for Your Budget in Nigeria — 2025 Guide',
    excerpt: 'From ₦400,000 to ₦2,000,000+, there is a right iPhone for every budget. Here is how to pick the one that makes the most sense for you.',
    category: 'Buying Guide',
    readTime: '7 min read',
    date: 'May 2025',
    featured: false,
    tags: ['iPhone', 'Budget', 'Buying Guide', '2025'],
    relatedCategories: ['iPhone'],
    emoji: '💡',
    sections: [
      { heading: 'Under ₦700,000 — iPhone 13', body: 'The iPhone 13 remains one of the best value iPhones you can buy in 2025. It still runs the latest iOS, the camera is genuinely excellent, and battery life is solid. The sweet spot for first-time iPhone buyers.' },
      { heading: '₦700,000 – ₦1,100,000 — iPhone 15', body: 'The iPhone 15 brings USB-C charging, a 48MP main camera, and the Dynamic Island cutout. It is a meaningful upgrade over any iPhone before it. For most people, the iPhone 15 is the best all-around iPhone in 2025.' },
      { heading: '₦1,100,000 – ₦1,600,000 — iPhone 15 Pro', body: 'The iPhone 15 Pro is for photographers, creators, and power users. The A17 Pro chip, 3x optical zoom, Action Button, and ProRes video make it a professional tool as much as a phone.' },
      { heading: 'Above ₦1,600,000 — iPhone 15 Pro Max', body: 'The Pro Max gets you the 5x periscope zoom, larger screen, and exceptional battery life. Unless you actively use zoom photography or need the larger size, the 15 Pro is better value.' },
    ],
  },
  {
    slug: 'how-to-transfer-data-to-new-iphone-nigeria',
    title: 'How to Transfer Everything to Your New iPhone (Step by Step)',
    excerpt: 'Switching from Android or upgrading from an older iPhone? This guide walks you through every method — iCloud, Quick Start, and manual transfer.',
    category: 'Tips & Tricks',
    readTime: '6 min read',
    date: 'May 2025',
    featured: false,
    tags: ['iPhone', 'Setup', 'Transfer', 'iCloud', 'Switch from Android'],
    relatedCategories: ['iPhone'],
    emoji: '🔄',
    sections: [
      { heading: 'Method 1: Quick Start (iPhone to iPhone)', body: 'Place your old iPhone next to your new one during setup. iOS transfers everything — apps, settings, photos, messages, and Wi-Fi passwords — wirelessly or via cable. Cable transfer is faster (30–60 min vs 2–4 hours wirelessly).' },
      { heading: 'Method 2: iCloud Backup + Restore', body: "Back up your old iPhone (Settings → [Your Name] → iCloud → iCloud Backup → Back Up Now), then restore on the new device during setup. You may need to temporarily upgrade your iCloud storage plan." },
      { heading: 'Method 3: Switching from Android', body: 'Download "Move to iOS" on Android before iPhone setup. It transfers contacts, messages, photos, videos, and bookmarks. For WhatsApp: go to WhatsApp → Settings → Chats → Move Chats to iPhone.' },
    ],
  },
  {
    slug: 'iphone-storage-guide-how-much-do-you-need',
    title: 'iPhone Storage Guide — 128GB, 256GB, or 512GB?',
    excerpt: "Choosing the wrong storage tier is one of the most common iPhone-buying mistakes. Here's exactly how to figure out how much you actually need.",
    category: 'Buying Guide',
    readTime: '4 min read',
    date: 'May 2025',
    featured: false,
    tags: ['iPhone', 'Storage', 'Buying Tips'],
    relatedCategories: ['iPhone'],
    emoji: '💾',
    sections: [
      { heading: '128GB — Who It\'s For', body: 'Primarily streaming apps, relying on cloud storage, average photo taker. Avoid if you record video regularly, download media offline, or use many large apps.' },
      { heading: '256GB — The Safe Default', body: 'For most people, 256GB is the sweet spot. The price difference over 128GB is typically ₦30,000–₦50,000 — worth it for the peace of mind over 3–4 years of use.' },
      { heading: '512GB — Who Actually Needs It', body: 'Content creators shooting ProRAW/ProRes, frequent travellers downloading offline media, and anyone who stores everything locally. For everyone else, it is money spent on space you will never fill.' },
      { heading: 'Can You Upgrade Later?', body: 'No. iPhone storage cannot be expanded. The decision you make at purchase is permanent. If you are between tiers, always go larger.' },
    ],
  },
  {
    slug: 'iphone-warranty-apple-care-nigeria-guide',
    title: 'iPhone Warranty and AppleCare+ in Nigeria — What You Need to Know',
    excerpt: 'Does Apple warranty apply in Nigeria? What does AppleCare+ actually cover? Full breakdown for Nigerian buyers.',
    category: 'Tips & Tricks',
    readTime: '5 min read',
    date: 'May 2025',
    featured: false,
    tags: ['Warranty', 'AppleCare', 'iPhone', 'Nigeria'],
    relatedCategories: ['iPhone', 'Mac', 'iPad', 'Apple Watch'],
    emoji: '🛡️',
    sections: [
      { heading: 'Standard Apple Warranty in Nigeria', body: "Every new iPhone comes with a 1-year limited warranty covering manufacturing defects. It is global — a Certo device is warrantied at any Apple Store worldwide. It does NOT cover accidental damage, battery degradation below 80%, or third-party repairs." },
      { heading: 'AppleCare+ — What It Covers', body: 'AppleCare+ extends coverage to 2 years and adds accidental damage protection. Up to 2 incidents per year — cracked screen for $29, other damage for $99. AppleCare+ with Theft and Loss replaces a stolen or lost device for $149.' },
      { heading: 'Local Repairs vs Apple Service', body: "Once a local repair shop opens your iPhone, Apple's warranty is voided. A repair that would cost ₦60,000 locally is free under warranty. Always contact Apple first for any issue under warranty." },
    ],
  },
];

module.exports = { SEED_POSTS };
