
// Certo — shared data & constants

let CERTO_RATE = 1590; // NGN per USD — updated live from ExchangeRate-API

const PRODUCTS = [
  {
    id: 'iphone-15-pro-256',
    name: 'iPhone 15 Pro',
    subtitle: '256GB · Natural Titanium',
    type: 'iPhone',
    condition: 'new',
    conditionNote: 'Sealed box, never activated. Ships directly from Apple US. Full Apple US warranty intact.',
    usdPrice: 999,
    images: ['iphone'],
    badge: 'Serial Verified',
    deliveryDays: '10–18 business days',
    inStock: true,
    featured: true,
    overview: [
      'Released September 2023',
      '6.1-inch Super Retina XDR display with ProMotion (120Hz)',
      '48MP Main camera with 3× optical zoom',
      'A17 Pro chip — first Pro-class chip in iPhone',
      'Titanium design with Action Button',
      'USB-C with USB 3 speeds (up to 10Gb/s)',
      '256GB storage',
    ],
    specs: [
      'A17 Pro chip',
      '48MP camera system',
      'USB-C with USB 3',
      'Titanium design',
      'Action Button',
      '6.1-inch ProMotion display',
    ],
    includes: [
      'iPhone 15 Pro',
      'USB-C Charge Cable (1 m)',
      'Documentation',
      'Certo 12-month warranty',
      'Serial verification certificate',
    ],
    features: [
      { title: 'A17 Pro chip', body: 'A Pro-class chip in iPhone for the first time. With a 6-core GPU, A17 Pro takes iPhone to the next level with a massive leap in graphics performance — enabling hardware-accelerated ray tracing and a new mesh shading pipeline.' },
      { title: 'Titanium design', body: 'iPhone 15 Pro has a strong and light aerospace-grade titanium design with a textured matte-glass back. It also features Ceramic Shield front, tougher than any smartphone glass, and a contoured edge that feels great in hand.' },
      { title: 'Pro camera system', body: '48MP Main camera with 100% Focus Pixels shoots 4K60 fps Dolby Vision. The 12MP Ultra Wide with autofocus captures macro photography. The 12MP 3× Telephoto brings distant subjects closer.' },
      { title: 'Action Button', body: 'A customizable button that launches your favorite feature instantly — Silent mode, Focus, Camera, Flashlight, Voice Memo, Magnifier, or any Shortcut you set.' },
      { title: 'USB-C with USB 3', body: 'Charge your Mac or iPad with the same cable. Transfer files up to 20× faster than USB 2. Connect to pro camera systems, external storage, and 4K displays directly from your iPhone.' },
    ],
    techSpecs: [
      { section: 'Chip', items: ['A17 Pro chip', '6-core CPU with 2 performance and 4 efficiency cores', '6-core GPU', '16-core Neural Engine'] },
      { section: 'Camera', items: ['48MP Main: 24 mm, ƒ/1.78 aperture, OIS', '12MP Ultra Wide: 13 mm, ƒ/2.2 aperture, autofocus', '12MP Telephoto: 77 mm, ƒ/2.8 aperture, 3× optical zoom', 'Night mode, Photonic Engine, Smart HDR 5'] },
      { section: 'Display', items: ['6.1-inch Super Retina XDR OLED', '2556-by-1179-pixel resolution at 460 ppi', 'ProMotion adaptive refresh rate up to 120Hz', 'Always-On display', '2000 nits peak outdoor brightness'] },
      { section: 'Storage', items: ['256GB'] },
      { section: 'Battery', items: ['Up to 23 hours video playback', 'Up to 20 hours streaming', 'Up to 75 hours audio playback', 'Fast-charge capable (50% in ~30 min with 20W adapter)'] },
      { section: 'Connectivity', items: ['5G (sub-6GHz and mmWave)', 'Wi-Fi 6 (802.11ax)', 'Bluetooth 5.3', 'Ultra Wideband chip', 'USB-C with USB 3 (up to 10Gb/s)'] },
      { section: 'Size and Weight', items: ['Height: 146.6 mm (5.77 inches)', 'Width: 70.6 mm (2.78 inches)', 'Depth: 8.25 mm (0.32 inch)', 'Weight: 187 g (6.60 ounces)'] },
    ],
  },
  {
    id: 'iphone-15-pro-512',
    name: 'iPhone 15 Pro',
    subtitle: '512GB · Black Titanium',
    type: 'iPhone',
    condition: 'new',
    conditionNote: 'Sealed box, never activated. Ships directly from Apple US. Full Apple US warranty intact.',
    usdPrice: 1199,
    images: ['iphone'],
    badge: 'Serial Verified',
    deliveryDays: '10–18 business days',
    inStock: true,
    featured: false,
    overview: [
      'Released September 2023',
      '6.1-inch Super Retina XDR display with ProMotion (120Hz)',
      '48MP Main camera with 3× optical zoom',
      'A17 Pro chip — first Pro-class chip in iPhone',
      'Titanium design with Action Button',
      'USB-C with USB 3 speeds (up to 10Gb/s)',
      '512GB storage',
    ],
    specs: [
      'A17 Pro chip',
      '48MP camera system',
      'USB-C with USB 3',
      'Titanium design',
      'Action Button',
      '512GB storage',
    ],
    includes: [
      'iPhone 15 Pro',
      'USB-C Charge Cable (1 m)',
      'Documentation',
      'Certo 12-month warranty',
      'Serial verification certificate',
    ],
    features: [
      { title: 'A17 Pro chip', body: 'A Pro-class chip in iPhone for the first time. Hardware-accelerated ray tracing and mesh shading pipeline deliver console-quality gaming on your phone.' },
      { title: '512GB storage', body: 'Store an enormous library of photos, 4K ProRes video, apps, and games — 512GB means you never have to choose what to keep.' },
      { title: 'Titanium design', body: 'Strong and light aerospace-grade titanium in sleek Black Titanium. Textured matte-glass back and Ceramic Shield front.' },
      { title: 'Pro camera system', body: '48MP Main shoots 4K60 fps Dolby Vision. 12MP Ultra Wide with autofocus for macro. 12MP 3× Telephoto.' },
      { title: 'USB-C with USB 3', body: 'Transfer files up to 20× faster than USB 2. Connect to external storage directly — perfect for offloading large ProRes video files on the go.' },
    ],
    techSpecs: [
      { section: 'Chip', items: ['A17 Pro chip', '6-core CPU with 2 performance and 4 efficiency cores', '6-core GPU', '16-core Neural Engine'] },
      { section: 'Camera', items: ['48MP Main: 24 mm, ƒ/1.78 aperture, OIS', '12MP Ultra Wide: 13 mm, ƒ/2.2 aperture, autofocus', '12MP Telephoto: 77 mm, ƒ/2.8 aperture, 3× optical zoom'] },
      { section: 'Display', items: ['6.1-inch Super Retina XDR OLED', '2556-by-1179 at 460 ppi', 'ProMotion up to 120Hz', 'Always-On display'] },
      { section: 'Storage', items: ['512GB'] },
      { section: 'Battery', items: ['Up to 23 hours video playback', 'Fast-charge capable'] },
      { section: 'Connectivity', items: ['5G', 'Wi-Fi 6 (802.11ax)', 'Bluetooth 5.3', 'USB-C with USB 3'] },
      { section: 'Size and Weight', items: ['Height: 146.6 mm', 'Width: 70.6 mm', 'Depth: 8.25 mm', 'Weight: 187 g'] },
    ],
  },
  {
    id: 'macbook-air-m3-13',
    name: 'MacBook Air M3',
    subtitle: '13-inch · 8GB RAM · 256GB SSD',
    type: 'MacBook',
    condition: 'new',
    conditionNote: 'Sealed box. Apple US retail unit. US warranty included.',
    usdPrice: 1099,
    images: ['macbook'],
    badge: 'Warranty Included',
    deliveryDays: '12–20 business days',
    inStock: true,
    featured: true,
    overview: [
      'Released March 2024',
      '13.6-inch Liquid Retina display with True Tone',
      '12MP Center Stage camera',
      '8GB unified memory',
      '256GB SSD',
      'Backlit Magic Keyboard with Touch ID',
      'MagSafe 3 charging port',
      'Two Thunderbolt 3 / USB 4 ports',
    ],
    specs: [
      'Apple M3 chip',
      '8-core CPU, 10-core GPU',
      '18-hour battery life',
      'Liquid Retina display',
      'MagSafe charging',
      '8GB unified memory',
    ],
    includes: [
      'MacBook Air',
      '30W USB-C Power Adapter',
      'USB-C Charge Cable (2 m)',
      'Documentation',
      'Certo 12-month warranty',
    ],
    features: [
      { title: 'Supercharged by M3', body: 'The Apple M3 chip brings even more speed and fluidity to everything you do — working across multiple apps, editing photos, or playing graphically demanding games.' },
      { title: 'Up to 18 hours of battery', body: 'MacBook Air delivers the same amazing performance whether running on battery or plugged in. Work all day and into the evening without reaching for a charger.' },
      { title: 'A brilliant display', body: 'The 13.6-inch Liquid Retina display supports 1 billion colors. Photos and videos pop with rich contrast and sharp detail, and text appears super crisp.' },
      { title: 'Look and sound your best', body: 'A 12MP Center Stage camera keeps you centered in video calls. Three mics and a four-speaker sound system with Spatial Audio make everything sound amazing.' },
      { title: 'Built for Apple Intelligence', body: 'Apple Intelligence is the personal intelligence system that helps you write, express yourself, and get things done effortlessly — with groundbreaking privacy protections.' },
      { title: 'Connect it all', body: 'MagSafe 3 charging port, two Thunderbolt 3 / USB 4 ports, a headphone jack, Wi-Fi 6E, and Bluetooth 5.3. Supports up to two external displays.' },
    ],
    techSpecs: [
      { section: 'Chip', items: ['Apple M3 chip', '8-core CPU with 4 performance and 4 efficiency cores', '10-core GPU', '16-core Neural Engine', '100GB/s memory bandwidth'] },
      { section: 'Memory', items: ['8GB unified memory'] },
      { section: 'Display', items: ['Liquid Retina display', '13.6-inch (diagonal) LED-backlit IPS', '2560-by-1664 native resolution at 224 ppi', '500 nits brightness', 'True Tone technology', 'Wide color (P3)'] },
      { section: 'Storage', items: ['256GB SSD'] },
      { section: 'Charging and Expansion', items: ['MagSafe 3 charging port', '3.5 mm headphone jack with high-impedance headphone support', 'Two Thunderbolt 3 / USB 4 ports (charging, DisplayPort, up to 40Gb/s)'] },
      { section: 'Battery', items: ['Up to 18 hours wireless web', 'Up to 18 hours Apple TV app movie playback', 'Built-in 52.6-watt-hour lithium-polymer battery', '30W USB-C Power Adapter included'] },
      { section: 'Audio', items: ['Four-speaker sound system with force-cancelling woofers', 'Spatial Audio with Dolby Atmos on built-in speakers', 'Three-mic array with directional beamforming', '3.5 mm headphone jack'] },
      { section: 'Wireless', items: ['Wi-Fi 6E (802.11ax)', 'Bluetooth 5.3'] },
      { section: 'Size and Weight', items: ['Height: 1.13 cm (0.44 inch)', 'Width: 30.41 cm (11.97 inches)', 'Depth: 21.5 cm (8.46 inches)', 'Weight: 1.24 kg (2.7 pounds)'] },
    ],
  },
  {
    id: 'macbook-air-m3-15',
    name: 'MacBook Air M3',
    subtitle: '15-inch · 16GB RAM · 512GB SSD',
    type: 'MacBook',
    condition: 'new',
    conditionNote: 'Sealed box. Apple US retail unit. US warranty included.',
    usdPrice: 1499,
    images: ['macbook'],
    badge: 'Warranty Included',
    deliveryDays: '12–20 business days',
    inStock: true,
    featured: false,
    overview: [
      'Released March 2024',
      '15.3-inch Liquid Retina display with True Tone',
      '12MP Center Stage camera',
      '16GB unified memory',
      '512GB SSD',
      'Backlit Magic Keyboard with Touch ID',
      'MagSafe 3 charging port',
      'Two Thunderbolt 3 / USB 4 ports',
    ],
    specs: [
      'Apple M3 chip',
      '8-core CPU, 10-core GPU',
      '18-hour battery life',
      '15.3" Liquid Retina display',
      'MagSafe charging',
      '16GB unified memory',
    ],
    includes: [
      'MacBook Air',
      '35W Dual USB-C Port Compact Power Adapter',
      'USB-C to MagSafe 3 Cable (2 m)',
      'Documentation',
      'Certo 12-month warranty',
    ],
    features: [
      { title: 'Supercharged by M3', body: 'The Apple M3 chip brings speed and fluidity to everything — from everyday multitasking to demanding creative work. With 16GB unified memory, it handles it all effortlessly.' },
      { title: 'Big, beautiful display', body: 'The 15.3-inch Liquid Retina display with 1 billion colors makes every photo, video, and document look stunning. The wide-view IPS display is great for collaboration too.' },
      { title: 'Up to 18 hours of battery', body: 'MacBook Air lasts all day on a single charge — whether you\'re on battery or plugged in, you get the same powerful performance.' },
      { title: 'Six-speaker sound system', body: 'Six speakers with force-cancelling woofers, Spatial Audio, and Dolby Atmos. It\'s the best-sounding MacBook Air, period.' },
      { title: 'Connect it all', body: 'MagSafe 3, two Thunderbolt 3 / USB 4 ports, a headphone jack, Wi-Fi 6E, and Bluetooth 5.3. Supports up to two external displays at once.' },
    ],
    techSpecs: [
      { section: 'Chip', items: ['Apple M3 chip', '8-core CPU with 4 performance and 4 efficiency cores', '10-core GPU', '16-core Neural Engine', '100GB/s memory bandwidth'] },
      { section: 'Memory', items: ['16GB unified memory'] },
      { section: 'Display', items: ['Liquid Retina display', '15.3-inch (diagonal) LED-backlit IPS', '2880-by-1864 native resolution at 224 ppi', '500 nits brightness', 'True Tone technology', 'Wide color (P3)'] },
      { section: 'Storage', items: ['512GB SSD'] },
      { section: 'Charging and Expansion', items: ['MagSafe 3 charging port', '3.5 mm headphone jack with high-impedance headphone support', 'Two Thunderbolt 3 / USB 4 ports (charging, DisplayPort, up to 40Gb/s)'] },
      { section: 'Battery', items: ['Up to 18 hours wireless web', 'Up to 18 hours Apple TV app movie playback', 'Built-in 66.5-watt-hour lithium-polymer battery', '35W Dual USB-C Port Compact Power Adapter included'] },
      { section: 'Audio', items: ['Six-speaker sound system with force-cancelling woofers', 'Spatial Audio with Dolby Atmos', 'Three-mic array with directional beamforming', '3.5 mm headphone jack'] },
      { section: 'Wireless', items: ['Wi-Fi 6E (802.11ax)', 'Bluetooth 5.3'] },
      { section: 'Size and Weight', items: ['Height: 1.15 cm (0.45 inch)', 'Width: 34.04 cm (13.40 inches)', 'Depth: 23.76 cm (9.35 inches)', 'Weight: 1.51 kg (3.3 pounds)'] },
    ],
  },
  {
    id: 'ipad-pro-11',
    name: 'iPad Pro 11-inch',
    subtitle: 'M4 · 256GB · Wi-Fi',
    type: 'iPad',
    condition: 'new',
    conditionNote: 'Sealed box. Apple US retail unit. US warranty included.',
    usdPrice: 999,
    images: ['ipad'],
    badge: 'Serial Verified',
    deliveryDays: '10–18 business days',
    inStock: true,
    featured: false,
    overview: [
      'Released May 2024',
      '11-inch Ultra Retina XDR display with ProMotion (120Hz)',
      'Apple M4 chip — the most powerful iPad ever',
      'Thinnest Apple product ever at 5.3 mm',
      'Apple Pencil Pro support',
      '256GB storage',
      'Wi-Fi 6E',
    ],
    specs: [
      'Apple M4 chip',
      'Ultra Retina XDR display',
      'Apple Pencil Pro support',
      'Wi-Fi 6E',
      'All-day battery',
      '5.3 mm thin',
    ],
    includes: [
      'iPad Pro',
      'USB-C Charge Cable (1 m)',
      'USB-C Power Adapter (20W)',
      'Documentation',
      'Certo 12-month warranty',
    ],
    features: [
      { title: 'Supercharged by M4', body: 'The Apple M4 chip brings a 10-core CPU and 10-core GPU to iPad Pro. It\'s the most powerful chip Apple has ever put in a product and makes iPad Pro a beast for creative pros.' },
      { title: 'Ultra Retina XDR display', body: 'The 11-inch Ultra Retina XDR display with ProMotion delivers an extreme dynamic range. Tandem OLED technology provides 1000 nits full-screen brightness and 1600 nits peak HDR brightness.' },
      { title: 'The thinnest Apple product ever', body: 'At just 5.3 mm thin and 444 g, iPad Pro 11-inch is remarkably light. It fits easily in a bag and feels incredible in your hands for extended use.' },
      { title: 'Apple Pencil Pro support', body: 'Apple Pencil Pro supports hover, squeeze, barrel roll, and haptic feedback. Find My built-in. It\'s the most advanced stylus experience Apple has made.' },
      { title: 'All-day battery', body: 'iPad Pro delivers up to 10 hours of battery life for browsing the web or watching video. USB-C charging with support for 45W fast charging.' },
    ],
    techSpecs: [
      { section: 'Chip', items: ['Apple M4 chip', '10-core CPU with 4 performance and 6 efficiency cores', '10-core GPU', '16-core Neural Engine', 'Hardware-accelerated ray tracing'] },
      { section: 'Display', items: ['Ultra Retina XDR display (Tandem OLED)', '11-inch (diagonal)', '2420-by-1668-pixel resolution at 264 ppi', 'ProMotion adaptive refresh rate up to 120Hz', '1000 nits full-screen / 1600 nits peak HDR brightness', 'True Tone, Wide color (P3)'] },
      { section: 'Storage', items: ['256GB'] },
      { section: 'Connectivity', items: ['Wi-Fi 6E (802.11ax)', 'Bluetooth 5.3', 'USB-C with USB 4 (up to 40Gb/s)'] },
      { section: 'Camera', items: ['12MP Wide back camera, ƒ/1.8 aperture', '4K video recording', '12MP Ultra Wide front camera, ƒ/2.4', 'Center Stage'] },
      { section: 'Battery', items: ['Up to 10 hours browsing', 'Up to 10 hours video', 'USB-C charging, 45W fast-charge capable'] },
      { section: 'Size and Weight', items: ['Height: 249.7 mm (9.83 inches)', 'Width: 177.5 mm (6.99 inches)', 'Depth: 5.3 mm (0.21 inch)', 'Weight: 444 g (0.98 pound)'] },
    ],
  },
  {
    id: 'airpods-pro-2',
    name: 'AirPods Pro',
    subtitle: '2nd Generation · USB-C',
    type: 'AirPods',
    condition: 'new',
    conditionNote: 'Sealed box. Apple US retail unit. US warranty included.',
    usdPrice: 249,
    images: ['airpods'],
    badge: 'Sealed Box',
    deliveryDays: '8–15 business days',
    inStock: true,
    featured: true,
    overview: [
      'Released September 2023 (USB-C)',
      'H2 chip powers next-level Active Noise Cancellation',
      'Adaptive Audio — new listening mode that blends ANC and Transparency',
      'Personalized Spatial Audio with dynamic head tracking',
      'Up to 6 hours listening / 30 hours total with case',
      'USB-C MagSafe Charging Case',
      'IP54 dust, sweat, and water resistance',
    ],
    specs: [
      'H2 chip',
      'Active Noise Cancellation',
      'Adaptive Audio',
      'Personalized Spatial Audio',
      'Up to 30hr battery (with case)',
      'IP54 water resistance',
    ],
    includes: [
      'AirPods Pro (2nd generation)',
      'MagSafe Charging Case with USB-C',
      'USB-C Charge Cable',
      'Ear tips (XS, S, M, L)',
      'Documentation',
    ],
    features: [
      { title: 'Next-level Active Noise Cancellation', body: 'AirPods Pro (2nd generation) deliver up to 2× more Active Noise Cancellation than AirPods Pro (1st generation), powered by the Apple H2 chip.' },
      { title: 'Adaptive Audio', body: 'A new listening mode that dynamically blends Active Noise Cancellation and Transparency mode, adapting to your environment in real time so you always hear exactly what you want.' },
      { title: 'Personalized Spatial Audio', body: 'Sound all around you. AirPods Pro use your iPhone\'s TrueDepth camera to map the unique shape of your ears, creating a listening experience tailored precisely to you.' },
      { title: 'All-day battery', body: 'Up to 6 hours of listening time with Active Noise Cancellation on — and up to 30 hours combined with the MagSafe Charging Case.' },
      { title: 'Hearing health features', body: 'Loud Sound Reduction protects your hearing. Conversation Awareness lowers volume and enhances voices when you start speaking. A clinical-grade hearing test available in iOS 18.' },
    ],
    techSpecs: [
      { section: 'Chip', items: ['Apple H2 chip'] },
      { section: 'Sound', items: ['Active Noise Cancellation', 'Transparency mode', 'Adaptive Audio', 'Personalized Spatial Audio with dynamic head tracking'] },
      { section: 'Battery', items: ['AirPods Pro: up to 6 hours listening (ANC on), up to 7 hours (ANC off)', 'MagSafe Case: up to 4 additional charges', 'Up to 30 hours total combined', 'Fast Fuel: 5 min charging = 1 hour listening'] },
      { section: 'Charging', items: ['MagSafe Charging Case with USB-C', 'Compatible with MagSafe, Qi2, Apple Watch charger, Qi charger'] },
      { section: 'Resistance', items: ['AirPods Pro: IP54 dust, sweat, and water resistant', 'MagSafe Case: IP54 dust and water resistant'] },
      { section: 'Sensors', items: ['Force sensor', 'Motion-detecting accelerometer', 'Speech-detecting accelerometer', 'Skin-detect sensor'] },
    ],
  },
  {
    id: 'apple-watch-s9-41',
    name: 'Apple Watch Series 9',
    subtitle: '41mm · Midnight Aluminium · GPS',
    type: 'Watch',
    condition: 'new',
    conditionNote: 'Sealed box. Apple US retail unit. US warranty included.',
    usdPrice: 399,
    images: ['watch'],
    badge: 'Warranty Included',
    deliveryDays: '8–15 business days',
    inStock: true,
    featured: false,
    overview: [
      'Released September 2023',
      '41mm Midnight Aluminium case with Sport Band',
      'S9 chip — the most powerful chip in a smartwatch',
      'Double tap gesture — control with a pinch of two fingers',
      'Always-on Retina display (2000 nits)',
      'Blood oxygen sensor, ECG, temperature sensor',
      'Crash Detection and Emergency SOS',
      'Up to 18 hours battery / 36 hours Low Power Mode',
    ],
    specs: [
      'S9 chip',
      'Double tap gesture',
      'Always-on Retina display',
      'Blood oxygen & ECG',
      'Crash Detection',
      'Up to 18 hours battery',
    ],
    includes: [
      'Apple Watch Series 9',
      'Sport Band (S/M and M/L)',
      'Magnetic Fast Charger to USB-C Cable (1 m)',
      'Documentation',
      'Certo 12-month warranty',
    ],
    features: [
      { title: 'Double tap', body: 'A magical new way to control Apple Watch without touching the display. Pinch your index finger and thumb together twice to answer a call, pause music, take a photo, or snooze an alarm.' },
      { title: 'S9 chip', body: 'The new S9 SiP enables a brighter display, faster processing, and more accurate Siri — all while improving power efficiency.' },
      { title: 'Health monitoring', body: 'Blood oxygen sensor, ECG app, temperature sensing, heart rate alerts, irregular rhythm notifications. Apple Watch Series 9 is your health companion on your wrist.' },
      { title: 'Crash Detection', body: 'If Apple Watch detects a severe car crash, it connects you with emergency services automatically — even if you\'re not conscious to do it yourself.' },
      { title: 'Always-on Retina display', body: '2000 nits brightness — twice as bright as Series 8. Always-on lets you see the time and your complications at a glance without raising your wrist.' },
    ],
    techSpecs: [
      { section: 'Chip', items: ['S9 SiP (System in Package)', '64-bit dual-core processor', '4-core Neural Engine'] },
      { section: 'Display', items: ['Always-on Retina LTPO OLED', '41mm: 352-by-430-pixel resolution at 326 ppi', '2000 nits peak brightness', 'Ion-X front glass'] },
      { section: 'Health Sensors', items: ['Blood oxygen sensor', 'Electrical heart sensor (ECG)', 'Third-generation optical heart sensor', 'Temperature sensor', 'High and low heart rate notifications'] },
      { section: 'Battery', items: ['Up to 18 hours normal mode', 'Up to 36 hours Low Power Mode', 'Fast charging capable (80% in ~45 min)'] },
      { section: 'Connectivity', items: ['GPS + GNSS (this model)', 'Wi-Fi 802.11b/g/n 2.4GHz and 5GHz', 'Bluetooth 5.3', 'Ultra Wideband chip'] },
      { section: 'Durability', items: ['WR50 water resistant (50 metres)', 'IP6X dust resistant', 'Crack-resistant front crystal', 'Aluminium case'] },
      { section: 'Size', items: ['41mm case: 41 × 35 × 10.7 mm', 'Weight: 31.9 g (without band)'] },
    ],
  },
  {
    id: 'airpods-pro-2-refurb',
    name: 'AirPods Pro',
    subtitle: '2nd Generation · USB-C · Refurbished',
    type: 'AirPods',
    condition: 'refurb',
    conditionNote: 'Grade A Apple-certified refurbished. Tested to full Apple functionality standards. Minor cosmetic marks may be present. New ear tips included. Covered by Apple\'s one-year limited warranty.',
    usdPrice: 179,
    images: ['airpods'],
    badge: 'Grade A Refurb',
    deliveryDays: '8–15 business days',
    inStock: false,
    featured: false,
    overview: [
      'Apple Certified Refurbished — quality products at great prices',
      'Rigorous refurbishment process prior to sale',
      'Covered by Apple\'s one-year limited warranty',
      'Covered by Apple\'s 14-day returns policy',
      'AppleCare+ can be purchased',
      'Engraving and gift wrap not available',
      'Same H2 chip and features as new model',
    ],
    specs: [
      'H2 chip',
      'Active Noise Cancellation',
      'Adaptive Audio',
      'Personalized Spatial Audio',
      'Up to 30hr battery (with case)',
      'Apple-certified refurbished',
    ],
    includes: [
      'AirPods Pro (2nd generation)',
      'Charging Case with USB-C',
      'USB-C Charge Cable',
      'New ear tips (XS, S, M, L)',
      'Documentation',
    ],
    features: [
      { title: 'Apple Certified Refurbished', body: 'Every refurbished product goes through Apple\'s full refurbishment process — functional testing, defective-part replacement, thorough cleaning, and repackaging with appropriate accessories.' },
      { title: 'Same great features', body: 'You get the exact same H2 chip, Active Noise Cancellation, Adaptive Audio, and Personalized Spatial Audio as the new model — at a lower price.' },
      { title: 'One-year Apple warranty', body: 'Covered by Apple\'s one-year limited warranty. The same warranty coverage as a new product. You can also purchase AppleCare+ to extend coverage.' },
      { title: 'Adaptive Audio', body: 'Dynamically blends Active Noise Cancellation and Transparency mode, adapting to your environment so you always hear exactly what you want.' },
      { title: 'Great battery life', body: 'Up to 6 hours listening with ANC on, up to 30 hours total with the charging case.' },
    ],
    techSpecs: [
      { section: 'Chip', items: ['Apple H2 chip'] },
      { section: 'Sound', items: ['Active Noise Cancellation', 'Transparency mode', 'Adaptive Audio', 'Personalized Spatial Audio with dynamic head tracking'] },
      { section: 'Battery', items: ['Up to 6 hours listening (ANC on)', 'Up to 30 hours total with case', 'Fast Fuel: 5 min = 1 hour listening'] },
      { section: 'Charging', items: ['Charging Case with USB-C', 'Compatible with MagSafe, Qi, Apple Watch charger'] },
      { section: 'Resistance', items: ['IP54 dust, sweat, and water resistant'] },
      { section: 'Refurbishment', items: ['Full functional testing', 'Defective part replacement', 'Thorough cleaning', 'New ear tips included', 'New packaging'] },
    ],
  },
];

const APPLECARE_OPTIONS = [
  {
    id: 'plus',
    name: 'AppleCare+',
    tagline: 'Full peace of mind',
    monthlyUsd: 9.99,
    annualUsd: 99,
    color: '#2563eb',
    benefits: ['2 years of coverage', 'Unlimited accidental damage repairs', 'Battery replacement if below 80%', 'Priority Apple Support 24/7'],
    activation: 'Download the AppleCare app or visit settings.apple.com within 60 days of receiving your device. You\'ll need your Apple ID and the device serial number.',
    recommended: true,
  },
  {
    id: 'one',
    name: 'AppleCare One',
    tagline: 'Standard protection',
    monthlyUsd: 4.99,
    annualUsd: null,
    color: '#0d9488',
    benefits: ['1 year of coverage', 'Hardware repairs', 'Apple Support access', 'Battery service'],
    activation: 'Visit applecareregistration.apple.com with your serial number within 30 days of receiving your device.',
    recommended: false,
  },
  {
    id: 'none',
    name: 'No Coverage',
    tagline: 'Certo warranty only',
    monthlyUsd: null,
    annualUsd: 0,
    color: '#6b7280',
    benefits: ['Certo 12-month warranty', 'Covers manufacturing defects', 'WhatsApp support', 'Serial verification included'],
    activation: 'Your Certo warranty begins on the delivery date and covers manufacturing defects for 12 months.',
    recommended: false,
  },
];

const ORDER_STATUSES = [
  { key: 'confirmed',  label: 'Order Confirmed',             done: true,  ts: 'Apr 22, 2026 · 9:14am',   note: 'Your order has been received and payment confirmed. We\'re preparing to procure your device.' },
  { key: 'purchased',  label: 'Purchased from Apple',         done: true,  ts: 'Apr 23, 2026 · 2:30pm',   note: 'Your iPhone 15 Pro has been purchased directly from Apple.com US.' },
  { key: 'transit_us', label: 'In Transit to US Partner',     done: true,  ts: 'Apr 24, 2026 · 11:05am',  note: 'Your device is on its way to our US logistics partner for inspection and packaging.' },
  { key: 'customs',    label: 'Customs Clearance',            done: false, ts: 'Expected Apr 27–28',       note: 'Your package is being processed through Nigerian customs. This typically takes 1–2 business days.' },
  { key: 'nigeria',    label: 'Arrived in Nigeria',           done: false, ts: 'Expected Apr 28–29',       note: '' },
  { key: 'delivery',   label: 'Out for Delivery',             done: false, ts: 'Expected Apr 29–30',       note: '' },
  { key: 'delivered',  label: 'Delivered',                    done: false, ts: 'Expected Apr 30',          note: '' },
];

const MOCK_ORDER = {
  id: 'CRT-2204-8841',
  product: PRODUCTS[0],
  applecare: APPLECARE_OPTIONS[0],
  qty: 1,
  customer: 'Adaeze Okoye',
  address: '14 Karimu Kotun St, Victoria Island, Lagos',
  state: 'Lagos',
  statuses: ORDER_STATUSES,
};

const TESTIMONIALS = [
  { name: 'Tobi A.',   location: 'Abuja',         product: 'MacBook Air M3',  text: 'I was scared to send over ₦2 million to a website. But the tracking page and WhatsApp updates every step of the way made it feel safe. My MacBook arrived sealed, serial checked, everything perfect.', stars: 5 },
  { name: 'Chioma N.', location: 'Lagos',          product: 'iPhone 15 Pro',   text: 'Bought my first iPhone through Certo after years of buying from Slot and getting burned. The forex explanation was clear, the price was honest, and it arrived in 14 days. I\'m a convert.', stars: 5 },
  { name: 'Emeka O.',  location: 'Port Harcourt',  product: 'AirPods Pro',     text: 'Serial number checked out on Apple\'s website. The packaging was perfect — clearly never opened. Certo is the only way I\'m buying Apple products from now on.', stars: 5 },
];

const useResponsive = () => {
  const [w, setW] = React.useState(() => window.innerWidth);
  React.useEffect(() => {
    const h = () => setW(window.innerWidth);
    window.addEventListener('resize', h);
    return () => window.removeEventListener('resize', h);
  }, []);
  return { isMobile: w < 640, isTablet: w < 1024, w };
};

Object.assign(window, { CERTO_RATE, PRODUCTS, APPLECARE_OPTIONS, ORDER_STATUSES, MOCK_ORDER, TESTIMONIALS, useResponsive });
